# Generated by Django 5.1 on 2024-08-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HAM_logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("", "home QTH"),
                    ("/n", "stationary outside home QTH"),
                    ("/P", "portable"),
                    ("/M", "mobile"),
                    ("/AM", "aeronautical mobile"),
                    ("/MM", "maritime mobile"),
                ],
                default="",
                max_length=3,
            ),
        ),
    ]
