# Generated by Django 5.1 on 2024-08-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HAM_logger", "0002_activity_operation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="operation_type",
            field=models.CharField(
                choices=[
                    (" ", "home QTH"),
                    ("/n", "stationary outside home QTH"),
                    ("/P", "portable"),
                    ("/M", "mobile"),
                    ("/AM", "aeronautical mobile"),
                    ("/MM", "maritime mobile"),
                ],
                default=" ",
                max_length=3,
            ),
        ),
    ]
