# Generated by Django 5.1 on 2024-08-24 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HAM_logger", "0003_alter_activity_operation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("time_added", models.TimeField(auto_now_add=True)),
                ("my_call", models.CharField(max_length=15)),
                ("your_call", models.CharField(max_length=15)),
                ("freq", models.CharField(max_length=10)),
                ("mode", models.CharField(max_length=3)),
                ("sent_report", models.IntegerField()),
                ("received_report", models.IntegerField()),
                (
                    "qso_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HAM_logger.activity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "QSOs",
            },
        ),
    ]
