# Generated by Django 5.1 on 2024-08-24 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HAM_logger", "0004_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Activities"},
        ),
    ]
