# Generated by Django 5.1 on 2024-08-24 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HAM_logger", "0005_alter_activity_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="qso_no",
            new_name="activity",
        ),
    ]
